### ISSUE TITLE
[DRAFT] 복셀 기반 월드

### ISSUE THREAD

**Issue by aor9** [Team-UEMO/Project#2]
### 지형 및 구조물 파괴 또는 변형
- 총을 발사하면 파괴되는 지형, 구조물 구현
- 지형이나 구조물이 복셀형태라면 더 간단하게 파괴할 수 있을 것 같다.
- 눈이나 모래에 총알이나 발자국을 남기는 효과 + 눈이나 모래가 총알에 튀는 효과

### 길찾기
- 맵이 복셀 형태로 되어있어서 그리드 기반으로 길찾기 가능
- 3D 맵에서도 더 쉽게 길찾기를 할 수 있을것으로 생각
- 경로 시각화 ( 맵이나 지형지물을 통과하지 않는 최적의 경로 )

### 복셀에 데이터 담기
- 적의 위치, 지형 타입 등을 복셀에 담아서 사용
- 서버측에서 해당 데이터 관리하면 좋을듯

**Comment by aor9** [comment]
### UE5의 Chaos Destruction 
- UE5에는 Chaos Destruction 이라는 매우 훌륭한 물리 기반 파괴 시스템 플러그인이 있음.
- 복셀 기반 월드를 만들어서 파괴하는 시스템을 만들어야하는지 의문.

**Comment by aor9** [comment]
## TODO
** 게임 규칙
- [ ] 게임 내 타이머 설정
- [ ] 한 명이 30킬 달성시 게임 종료

** 무기 추가
- [ ] 무기 스왑 시스템 (1번 주무기, 2번 피스톨, 3번 칼)
- [ ] 스나이퍼 라이플, 샷건 등 추가

** 아이템 추가
- [ ] 체력 회복 아이템 추가
- [ ] 버프 아이템 추가

** 킬 로그 및 K/D UI
- [ ] 누가 어떤 무기로 누굴 죽였는지 확인하는 킬 로그 시스템
- [ ] 누가 몇킬 몇데스인지 Tab 키를 눌러 확인하는 UI

**Interactive한 지형 및 환경**
- [ ] 데미지를 입으면 파괴되는 건물
- [ ] Niagara GPU Particles ( 총이나 폭탄에 먼지같은거 날리는 효과 )
